[workspace]
members = [
    "zrd-core",
    "zrd-gui",
    "zrd",
]
resolver = "2"

[workspace.package]
version = "0.1.1"
edition = "2021"
authors = ["Doug Lance"]
license = "MIT"
repository = "https://github.com/douglance/zrd"

[profile.dev]
opt-level = 3

[profile.release]
lto = "thin"
